apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-auth-app
  template:
    metadata:
      labels:
        app: user-auth-app
    spec:
      containers:
      - name: user-auth-app
        image: sathamdocker/user-authentication-service-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: user-auth-app-service
spec:
  selector:
    app: user-auth-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
