apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-auth-app
  template:
    metadata:
      labels:
        app: user-auth-app
    spec:
      containers:
      - name: user-auth-app
        image: sathamdocker/user-authentication-service-app:latest
        ports:
        - containerPort: 80
